jeux = [
    ("The Legend of Zelda: Breath of the Wild", 1, 1),
    ("Red Dead Redemption 2", 1, 32),
    ("The Witcher 3: Wild Hunt", 1, 1),
    ("Dark Souls III", 1, 6),
    ("Elden Ring", 1, 4),
    ("Cyberpunk 2077", 1, 1),
    ("Grand Theft Auto V", 1, 30),
    ("Minecraft", 1, 100),
    ("Fortnite", 1, 100),
    ("League of Legends", 1, 10),
    ("Dota 2", 1, 10),
    ("Counter-Strike: Global Offensive", 1, 10),
    ("Valorant", 1, 10),
    ("Overwatch 2", 1, 10),
    ("Call of Duty: Warzone", 1, 150),
    ("Apex Legends", 1, 60),
    ("PUBG: Battlegrounds", 1, 100),
    ("Hollow Knight", 1, 1),
    ("Celeste", 1, 1),
    ("Undertale", 1, 1),
    ("Stardew Valley", 1, 4),
    ("Animal Crossing: New Horizons", 1, 8),
    ("Super Mario Odyssey", 1, 2),
    ("Super Smash Bros. Ultimate", 1, 8),
    ("Mario Kart 8 Deluxe", 1, 12),
    ("Horizon Zero Dawn", 1, 1),
    ("God of War", 1, 1),
    ("God of War: Ragnarok", 1, 1),
    ("Bloodborne", 1, 5),
    ("Sekiro: Shadows Die Twice", 1, 1),
    ("Monster Hunter: World", 1, 4),
    ("Monster Hunter Rise", 1, 4),
    ("Resident Evil 2 Remake", 1, 1),
    ("Resident Evil 4 Remake", 1, 1),
    ("Silent Hill 2", 1, 1),
    ("Metal Gear Solid V: The Phantom Pain", 1, 1),
    ("Fallout 4", 1, 1),
    ("Fallout: New Vegas", 1, 1),
    ("Skyrim", 1, 1),
    ("Persona 5 Royal", 1, 1),
    ("Final Fantasy VII Remake", 1, 1),
    ("Final Fantasy XVI", 1, 1),
    ("Dragon Quest XI", 1, 1),
    ("Nier: Automata", 1, 1),
    ("Nier Replicant", 1, 1),
    ("Bayonetta 3", 1, 1),
    ("Metroid Prime Remastered", 1, 1),
    ("Splatoon 3", 1, 8),
    ("Fire Emblem: Three Houses", 1, 1),
    ("Xenoblade Chronicles 3", 1, 1),
    ("Tunic", 1, 1),
    ("Death Stranding", 1, 1),
    ("No Man's Sky", 1, 32),
    ("Hades", 1, 1),
    ("Dead Cells", 1, 1),
    ("Slay the Spire", 1, 1),
    ("Terraria", 1, 8),
    ("Factorio", 1, 100),
    ("Don't Starve Together", 1, 6),
    ("The Binding of Isaac", 1, 2),
    ("Cuphead", 1, 2),
    ("Disco Elysium", 1, 1),
    ("Baldur's Gate 3", 1, 4),
    ("Divinity: Original Sin 2", 1, 4),
    ("The Outer Worlds", 1, 1),
    ("Starfield", 1, 1),
    ("Diablo IV", 1, 4),
    ("Destiny 2", 1, 6),
    ("Warframe", 1, 4),
    ("Genshin Impact", 1, 4),
    ("Tower of Fantasy", 1, 100),
    ("Battlefield 2042", 1, 128),
    ("Mortal Kombat 11", 1, 2),
    ("Tekken 8", 1, 2),
    ("Street Fighter 6", 1, 2),
    ("Guilty Gear Strive", 1, 2),
    ("Among Us", 4, 15),
    ("Phasmophobia", 1, 4),
    ("The Forest", 1, 8),
    ("Sons of the Forest", 1, 8),
    ("Subnautica", 1, 1),
    ("Raft", 1, 4),
    ("Escape from Tarkov", 1, 5),
    ("The Sims 4", 1, 1),
    ("Cities: Skylines", 1, 1),
    ("Anno 1800", 1, 4),
    ("Crusader Kings III", 1, 32),
    ("Hearts of Iron IV", 1, 32),
    ("Europa Universalis IV", 1, 32),
    ("Age of Empires IV", 1, 8),
    ("Civilization VI", 1, 12),
    ("Frostpunk", 1, 1),
    ("Oxygen Not Included", 1, 1),
    ("RimWorld", 1, 1),
    ("Project Zomboid", 1, 16),
    ("DayZ", 1, 60),
    ("ARK: Survival Evolved", 1, 100),
    ("Rust", 1, 100),
    ("Dead by Daylight", 5, 5),
    ("Friday the 13th: The Game", 1, 8)
]
nb_joueurs = 0

def game_Selection(int: nb_joueurs): # type: ignore
    jeux_possible = []
    while i < len(jeux):
        if i[2] >=  nb_joueurs:
            jeux_possible.append(i-2)
            i+3
        else:
            i+3
    print(jeux_possible)
    return jeux_possible


nbj = int(input("Entrez le nombre de joueurs: "))
game_Selection(nbj)