jeux = [
    ("The Legend of Zelda: Breath of the Wild", 1, 1),
    ("Red Dead Redemption 2", 1, 32),
    ("The Witcher 3: Wild Hunt", 1, 1),
    ("Dark Souls III", 1, 6),
    ("Elden Ring", 1, 4),
    ("Cyberpunk 2077", 1, 1),
    ("Grand Theft Auto V", 1, 30),
    ("Minecraft", 1, 100),
    ("Fortnite", 1, 100),
    ("League of Legends", 1, 10),
    ("Dota 2", 1, 10),
    ("Counter-Strike: Global Offensive", 1, 10),
    ("Valorant", 1, 10),
    ("Overwatch 2", 1, 10),
    ("Call of Duty: Warzone", 1, 150),
    ("Apex Legends", 1, 60),
    ("PUBG: Battlegrounds", 1, 100),
    ("Hollow Knight", 1, 1),
    ("Celeste", 1, 1),
    ("Undertale", 1, 1),
    ("Stardew Valley", 1, 4),
    ("Animal Crossing: New Horizons", 1, 8),
    ("Super Mario Odyssey", 1, 2),
    ("Super Smash Bros. Ultimate", 1, 8),
    ("Mario Kart 8 Deluxe", 1, 12),
    ("Horizon Zero Dawn", 1, 1),
    ("God of War", 1, 1),
    ("God of War: Ragnarok", 1, 1),
    ("Bloodborne", 1, 5),
    ("Sekiro: Shadows Die Twice", 1, 1),
    ("Monster Hunter: World", 1, 4),
    ("Monster Hunter Rise", 1, 4),
    ("Resident Evil 2 Remake", 1, 1),
    ("Resident Evil 4 Remake", 1, 1),
    ("Silent Hill 2", 1, 1),
    ("Metal Gear Solid V: The Phantom Pain", 1, 1),
    ("Fallout 4", 1, 1),
    ("Fallout: New Vegas", 1, 1),
    ("Skyrim", 1, 1),
    ("Persona 5 Royal", 1, 1),
    ("Final Fantasy VII Remake", 1, 1),
    ("Final Fantasy XVI", 1, 1),
    ("Dragon Quest XI", 1, 1),
    ("Nier: Automata", 1, 1),
    ("Nier Replicant", 1, 1),
    ("Bayonetta 3", 1, 1),
    ("Metroid Prime Remastered", 1, 1),
    ("Splatoon 3", 1, 8),
    ("Fire Emblem: Three Houses", 1, 1),
    ("Xenoblade Chronicles 3", 1, 1),
    ("Tunic", 1, 1),
    ("Death Stranding", 1, 1),
    ("No Man's Sky", 1, 32),
    ("Hades", 1, 1),
    ("Dead Cells", 1, 1),
    ("Slay the Spire", 1, 1),
    ("Terraria", 1, 8),
    ("Factorio", 1, 100),
    ("Don't Starve Together", 1, 6),
    ("The Binding of Isaac", 1, 2),
    ("Cuphead", 1, 2),
    ("Disco Elysium", 1, 1),
    ("Baldur's Gate 3", 1, 4),
    ("Divinity: Original Sin 2", 1, 4),
    ("The Outer Worlds", 1, 1),
    ("Starfield", 1, 1),
    ("Diablo IV", 1, 4),
    ("Destiny 2", 1, 6),
    ("Warframe", 1, 4),
    ("Genshin Impact", 1, 4),
    ("Tower of Fantasy", 1, 100),
    ("Battlefield 2042", 1, 128),
    ("Mortal Kombat 11", 1, 2),
    ("Tekken 8", 1, 2),
    ("Street Fighter 6", 1, 2),
    ("Guilty Gear Strive", 1, 2),
    ("Among Us", 4, 15),
    ("Phasmophobia", 1, 4),
    ("The Forest", 1, 8),
    ("Sons of the Forest", 1, 8),
    ("Subnautica", 1, 1),
    ("Raft", 1, 4),
    ("Escape from Tarkov", 1, 5),
    ("The Sims 4", 1, 1),
    ("Cities: Skylines", 1, 1),
    ("Anno 1800", 1, 4),
    ("Crusader Kings III", 1, 32),
    ("Hearts of Iron IV", 1, 32),
    ("Europa Universalis IV", 1, 32),
    ("Age of Empires IV", 1, 8),
    ("Civilization VI", 1, 12),
    ("Frostpunk", 1, 1),
    ("Oxygen Not Included", 1, 1),
    ("RimWorld", 1, 1),
    ("Project Zomboid", 1, 16),
    ("DayZ", 1, 60),
    ("ARK: Survival Evolved", 1, 100),
    ("Rust", 1, 100),
    ("Dead by Daylight", 5, 5),
    ("Friday the 13th: The Game", 1, 8),
    ("The Legend of Zelda: Breath of the Wild", 1, 1),
    ("The Legend of Zelda: Tears of the Kingdom", 1, 1),
    ("Super Mario Odyssey", 1, 2),
    ("Super Smash Bros. Ultimate", 1, 8),
    ("Mario Kart 8 Deluxe", 1, 12),
    ("Animal Crossing: New Horizons", 1, 8),
    ("Luigi's Mansion 3", 1, 8),
    ("Splatoon 3", 1, 8),
    ("Fire Emblem: Three Houses", 1, 1),
    ("Fire Emblem Engage", 1, 1),
    ("Xenoblade Chronicles 3", 1, 1),
    ("Pokémon Scarlet & Violet", 1, 4),
    ("Pokémon Legends: Arceus", 1, 1),
    ("Pokémon Sword & Shield", 1, 4),
    ("Kirby and the Forgotten Land", 1, 2),
    ("Metroid Prime Remastered", 1, 1),
    ("Metroid Dread", 1, 1),
    ("Bayonetta 3", 1, 1),
    ("Octopath Traveler", 1, 1),
    ("Octopath Traveler II", 1, 1),
    ("Triangle Strategy", 1, 1),
    ("Live A Live", 1, 1),
    ("Bravely Default II", 1, 1),
    ("Monster Hunter Rise", 1, 4),
    ("Monster Hunter Stories 2: Wings of Ruin", 1, 1),
    ("Hyrule Warriors: Age of Calamity", 1, 2),
    ("Mario Party Superstars", 1, 4),
    ("Super Mario Party", 1, 4),
    ("Donkey Kong Country: Tropical Freeze", 1, 2),
    ("New Super Mario Bros. U Deluxe", 1, 4),
    ("Super Mario 3D World + Bowser’s Fury", 1, 4),
    ("Captain Toad: Treasure Tracker", 1, 2),
    ("Yoshi's Crafted World", 1, 2),
    ("The World Ends With You: Final Remix", 1, 1),
    ("NEO: The World Ends With You", 1, 1),
    ("Shin Megami Tensei V", 1, 1),
    ("Danganronpa: Trigger Happy Havoc", 1, 1),
    ("Danganronpa 2: Goodbye Despair", 1, 1),
    ("Danganronpa V3: Killing Harmony", 1, 1),
    ("Astral Chain", 1, 1),
    ("Persona 5 Royal", 1, 1),
    ("Persona 4 Golden", 1, 1),
    ("Persona 3 Portable", 1, 1),
    ("The Great Ace Attorney Chronicles", 1, 1),
    ("Phoenix Wright: Ace Attorney Trilogy", 1, 1),
    ("Cuphead", 1, 2),
    ("Hollow Knight", 1, 1),
    ("Celeste", 1, 1),
    ("Undertale", 1, 1),
    ("Stardew Valley", 1, 4),
    ("Terraria", 1, 8),
    ("Hades", 1, 1),
    ("Dead Cells", 1, 1),
    ("Slay the Spire", 1, 1),
    ("The Binding of Isaac: Repentance", 1, 2),
    ("Tunic", 1, 1),
    ("No Man's Sky", 1, 32),
    ("Disco Elysium", 1, 1),
    ("Baldur's Gate 3", 1, 4),
    ("Divinity: Original Sin 2", 1, 4),
    ("Diablo III: Eternal Collection", 1, 4),
    ("Diablo IV", 1, 4),
    ("Minecraft", 1, 100),
    ("Among Us", 4, 15),
    ("Overcooked! All You Can Eat", 1, 4),
    ("Overcooked 2", 1, 4),
    ("Moving Out", 1, 4),
    ("Lego Star Wars: The Skywalker Saga", 1, 2),
    ("Lego Harry Potter Collection", 1, 2),
    ("Lego Marvel Super Heroes", 1, 2),
    ("Lego City Undercover", 1, 2),
    ("Lego Jurassic World", 1, 2),
    ("Just Dance 2024", 1, 6),
    ("Just Dance 2023", 1, 6),
    ("The Jackbox Party Pack 10", 1, 8),
    ("The Jackbox Party Pack 9", 1, 8),
    ("The Jackbox Party Pack 8", 1, 8),
    ("FIFA 23 Legacy Edition", 1, 4),
    ("NBA 2K24", 1, 4),
    ("Pikmin 4", 1, 2),
    ("Pikmin 3 Deluxe", 1, 2),
    ("Tetris 99", 1, 99),
    ("Pac-Man 99", 1, 99),
    ("Kirby’s Return to Dream Land Deluxe", 1, 4),
    ("Fae Farm", 1, 4),
    ("Disney Dreamlight Valley", 1, 1),
    ("Harvestella", 1, 1),
    ("Rune Factory 5", 1, 1),
    ("Story of Seasons: Friends of Mineral Town", 1, 1),
    ("Story of Seasons: Pioneers of Olive Town", 1, 1),
    ("My Time at Portia", 1, 1),
    ("My Time at Sandrock", 1, 1),
    ("Spiritfarer", 1, 1)
]
nb_joueurs = 0

def game_Selection(nb_joueurs:int): # type: ignore
    jeux_possible = []
    for i in range(0, len(jeux)):
        if jeux[i][2] >=  nb_joueurs:
            jeux_possible.append(jeux[i][0])
    for j in range(len(jeux_possible)):
        print(jeux_possible[j])
    return jeux_possible


nbj = int(input("Entrez le nombre de joueurs: "))
print()
game_Selection(nbj)
print()