#!/usr/bin/env python3
from clippy_fact_buddy import FactDatabase, DB_PATH

SEED_FACTS = [
    ("Fur-bearing mammals like foxes and otters are sometimes called furry animals because of their dense body hair.", ["furry", "animals"]),
    ("The furry fandom celebrates anthropomorphic animal characters across art, costumes, and performance.", ["furry", "community"]),
    ("Fursuits are custom costumes that many furry fans build to represent their animal alter egos.", ["furry", "crafting"]),
    ("Furry art often blends animal features with human expressions and clothing.", ["furry", "art"]),
    ("The term furry emerged in the 1980s as science fiction and fantasy fandom explored anthropomorphic animals.", ["furry", "history"]),
    ("Many furry conventions feature panels about costume building, character design, and social community norms.", ["furry", "events"]),
    ("A fursona is an individual's personalized anthropomorphic animal identity in the furry community.", ["furry", "identity"]),
    ("Some furry costumes can take hundreds of hours and several thousand dollars to complete.", ["furry", "crafting"]),
    ("Furry art spans digital painting, sculpture, comics, and animation.", ["furry", "art"]),
    ("Anthropomorphic animals appear in storytelling traditions around the world, from fables to modern cartoons.", ["furry", "culture"]),
    ("Warframe launched in 2013 and has grown into a persistent cooperative online action game.", ["warframe", "gaming"]),
    ("Players control biomechanical suits called Warframes, each with unique abilities and playstyles.", ["warframe", "gameplay"]),
    ("Warframes are powered by an energy source called void energy that fuels their special powers.", ["warframe", "lore"]),
    ("The game Warframe receives regular updates and new story content from developer Digital Extremes.", ["warframe", "updates"]),
    ("Players in Warframe can customize their Warframes, weapons, and companions with mods.", ["warframe", "customization"]),
    ("The Tenno in Warframe are ancient warriors who pilot biomechanical suits called Warframes.", ["warframe", "lore"]),
    ("Warframe includes open-world zones where players can explore, complete missions, and hunt enemies.", ["warframe", "open-world"]),
    ("The game has a large community that shares builds, strategies, and fan-created artwork.", ["warframe", "community"]),
    ("Many players collect multiple Warframes to experiment with different combat roles.", ["warframe", "collection"]),
    ("Warframe's in-game economy uses platinum as premium currency for trading and purchases.", ["warframe", "economy"]),
    ("Hydrogen is the most abundant chemical element in the visible universe.", ["atoms", "chemistry"]),
    ("An atom consists of a nucleus of protons and neutrons surrounded by electrons.", ["atoms", "physics"]),
    ("There are 118 confirmed chemical elements in the periodic table.", ["atoms", "chemistry"]),
    ("Electrons occupy atomic orbitals rather than orbiting the nucleus like planets.", ["atoms", "quantum"]),
    ("Most of an atom's mass is concentrated in its nucleus.", ["atoms", "physics"]),
    ("A carbon atom can form four covalent bonds with other atoms.", ["atoms", "chemistry"]),
    ("Neutrons have no electric charge and help stabilize atomic nuclei.", ["atoms", "physics"]),
    ("The periodic table arranges elements by increasing atomic number.", ["atoms", "chemistry"]),
    ("Atoms can join to form molecules by sharing or transferring electrons.", ["atoms", "chemistry"]),
    ("Quantum mechanics is the branch of physics that explains atomic behavior.", ["atoms", "quantum"]),
    ("The Milky Way galaxy contains more than 100 billion stars.", ["space", "astronomy"]),
    ("Earth completes one orbit around the Sun in about 365.25 days.", ["space", "astronomy"]),
    ("Jupiter is the largest planet in our Solar System.", ["space", "planets"]),
    ("A light year is the distance that light travels in one year.", ["space", "physics"]),
    ("Black holes form when massive stars collapse under gravity.", ["space", "astrophysics"]),
    ("Mars is home to Olympus Mons, the tallest volcano in the Solar System.", ["space", "planets"]),
    ("The Moon's gravity causes the tides on Earth.", ["space", "earth"]),
    ("Venus rotates in the opposite direction from most other planets.", ["space", "planets"]),
    ("Saturn's rings are made of ice and rock particles.", ["space", "planets"]),
    ("The Sun is a massive ball of hot plasma that powers life on Earth.", ["space", "astronomy"]),
    ("Blue whales are the largest animals ever known.", ["animals", "nature"]),
    ("Octopuses have three hearts and blue blood.", ["animals", "biology"]),
    ("Honeybees communicate using a waggle dance.", ["animals", "behavior"]),
    ("Cheetahs are the fastest land animals, capable of speeds over 60 miles per hour.", ["animals", "speed"]),
    ("Some turtles can absorb oxygen through their skin or cloaca.", ["animals", "biology"]),
    ("Elephants can recognize themselves in mirrors.", ["animals", "behavior"]),
    ("Penguins are flightless birds adapted for aquatic life.", ["animals", "nature"]),
    ("Bats are the only mammals capable of sustained flight.", ["animals", "biology"]),
    ("A group of crows is called a murder.", ["animals", "language"]),
    ("Koalas can sleep up to 20 hours a day.", ["animals", "behavior"]),
    ("The Great Pyramid of Giza was completed over 4,500 years ago.", ["history", "ancient"]),
    ("Johannes Gutenberg invented the movable-type printing press around 1440.", ["history", "technology"]),
    ("The Roman Empire covered three continents at its height.", ["history", "empire"]),
    ("The Magna Carta was signed in 1215 and limited the power of English kings.", ["history", "law"]),
    ("Ancient Athens is often credited with creating the first democracy.", ["history", "politics"]),
    ("The Silk Road connected East Asia and Europe for centuries.", ["history", "trade"]),
    ("The Industrial Revolution began in the late 18th century.", ["history", "technology"]),
    ("The Wright brothers made the first powered airplane flight in 1903.", ["history", "aviation"]),
    ("The Berlin Wall fell in 1989, symbolizing the end of the Cold War.", ["history", "politics"]),
    ("The Rosetta Stone helped scholars decipher ancient Egyptian hieroglyphs.", ["history", "language"]),
    ("The first programmable computer was developed during the 1940s.", ["technology", "computing"]),
    ("Moore's Law observes that transistor counts double approximately every two years.", ["technology", "semiconductors"]),
    ("Tim Berners-Lee invented the World Wide Web in 1989.", ["technology", "internet"]),
    ("GPS relies on a network of satellites orbiting Earth.", ["technology", "navigation"]),
    ("Lithium-ion batteries power most modern portable electronics.", ["technology", "energy"]),
    ("Artificial intelligence systems learn patterns from large datasets.", ["technology", "ai"]),
    ("The first smartphone combined telephony and computing features in 1992.", ["technology", "mobile"]),
    ("3D printing builds objects layer by layer from digital designs.", ["technology", "manufacturing"]),
    ("Solar panels convert sunlight into electricity using photovoltaic cells.", ["technology", "energy"]),
    ("Encryption protects digital data by scrambling it into an unreadable form.", ["technology", "security"]),
    ("Tomatoes are botanically fruits but are used as vegetables in cooking.", ["food", "biology"]),
    ("Honey is the only food that can remain edible indefinitely.", ["food", "preservation"]),
    ("Chocolate is made from fermented cacao beans.", ["food", "production"]),
    ("Sushi is a Japanese dish originally based on fermented rice and fish.", ["food", "culture"]),
    ("Bread was one of the first widely processed foods created by humans.", ["food", "history"]),
    ("Pasta may have ancient origins in Asia before becoming associated with Italy.", ["food", "history"]),
    ("Vanilla comes from the pods of an orchid native to Mexico.", ["food", "botany"]),
    ("Coffee beans are the seeds of the fruit of Coffea plants.", ["food", "botany"]),
    ("Cheese is produced by fermenting milk with cultures and enzymes.", ["food", "production"]),
    ("Kimchi is a traditional Korean fermented vegetable dish.", ["food", "culture"]),
    ("The Mona Lisa was painted by Leonardo da Vinci in the early 1500s.", ["art", "history"]),
    ("Impressionism emphasized light and color over precise detail.", ["art", "style"]),
    ("Michelangelo carved the statue of David from a single block of marble.", ["art", "sculpture"]),
    ("The Renaissance was a European cultural movement from the 14th to 17th century.", ["art", "history"]),
    ("Lost-wax casting is a method of making metal sculptures from wax models.", ["art", "technique"]),
    ("A fresco is a mural painted directly onto wet plaster.", ["art", "technique"]),
    ("Perspective creates the illusion of depth on a flat surface.", ["art", "principles"]),
    ("Cubism fragmented objects into geometric shapes in the early 20th century.", ["art", "style"]),
    ("The color wheel groups colors into primary, secondary, and tertiary hues.", ["art", "theory"]),
    ("Typography is the art and technique of arranging printed text.", ["art", "design"]),
    ("Rainbows form when sunlight refracts and reflects inside water droplets.", ["nature", "weather"]),
    ("Mangrove forests grow in coastal saltwater environments and protect shorelines.", ["nature", "ecology"]),
    ("A desert is defined by low precipitation, not temperature.", ["nature", "climate"]),
    ("Volcanoes form when magma reaches the Earth's surface.", ["nature", "geology"]),
    ("Earth's atmosphere is composed mostly of nitrogen and oxygen.", ["nature", "earth"]),
    ("Coral reefs support more marine life per area than most ecosystems.", ["nature", "marine"]),
    ("A glacier is a large, slow-moving river of ice.", ["nature", "geology"]),
    ("The Amazon rainforest produces about 20% of the world's oxygen.", ["nature", "ecology"]),
    ("Thunder is caused by the rapid expansion of air heated by lightning.", ["nature", "weather"]),
    ("Bioluminescence is the production of light by living organisms.", ["nature", "biology"]),
]


def seed_database():
    db = FactDatabase(DB_PATH)
    inserted = 0
    for fact_text, tags in SEED_FACTS:
        db.add_fact(fact_text, tags)
        inserted += 1
    print(f"Inserted {inserted} seed facts into {DB_PATH}")


if __name__ == "__main__":
    seed_database()
